// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.Entities.Context;

#nullable disable

namespace TaxCalculator.Entities.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230508144354_InitialTaxCalculatorCreate")]
    partial class InitialTaxCalculatorCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCalculator.Entities.Entities.PostalCodeInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CalculationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FlatRateTax")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("FlatValueTax")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("PostalCodeInfo");
                });

            modelBuilder.Entity("TaxCalculator.Entities.Entities.ProgressiveTaxRate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostalCodeInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TaxBracketEnd")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal>("TaxBracketStart")
                        .HasColumnType("decimal(38, 2)");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeInfoId");

                    b.ToTable("ProgressiveTaxRate");
                });

            modelBuilder.Entity("TaxCalculator.Entities.Entities.TaxCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostalCodeInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 10)");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeInfoId");

                    b.ToTable("TaxCalculation");
                });

            modelBuilder.Entity("TaxCalculator.Entities.Entities.ProgressiveTaxRate", b =>
                {
                    b.HasOne("TaxCalculator.Entities.Entities.PostalCodeInfo", "PostalCodeInfo")
                        .WithMany()
                        .HasForeignKey("PostalCodeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostalCodeInfo");
                });

            modelBuilder.Entity("TaxCalculator.Entities.Entities.TaxCalculation", b =>
                {
                    b.HasOne("TaxCalculator.Entities.Entities.PostalCodeInfo", "PostalCodeInfo")
                        .WithMany()
                        .HasForeignKey("PostalCodeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostalCodeInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
